#ifndef CPP_CONCURR_INCLUDE_DETAIL_PRECOMPILED_HPP
#define CPP_CONCURR_INCLUDE_DETAIL_PRECOMPILED_HPP

#include "Utils.hpp"
#include "ThreadGuard.hpp"

#endif //CPP_CONCURR_INCLUDE_DETAIL_PRECOMPILED_HPP
